### ISSUE TITLE
[feature request] route to generate tokens with equal or less access

### ISSUE THREAD

**Issue by nullhack** [frankie567/fastapi-users#220] opened 2020-06-03 19:37 UTC
The idea is that if a token can use some scopes (e.g. user:register, user:read, user:delete), he should be able to create a token for equal or smaller access.
Let's say, I have a token that expires in 1 day and has permissions `user:register, user:read`, I can generate a new token with just `user:read`, then I can make a request:

`www.host.com/token`

Passing `permissions=['user:read']` or something similar and the return is a token that can be used up to the same expiration (1 day) and allows me to access any request that depends on this or no scope

**Comment by frankie567** [comment] 2020-06-15 12:31
I'll close it as a duplicate of #219 ; I think this is more or less the same discussion.

**Closed by frankie567** 2020-06-15 12:31 UTC
